myapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'myapp'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('dashboard/', views.dashboard, name = 'dashboard_url'),
    path('login/', LoginView.as_view(), name='login_url'),
    path('register/', views.register, name='register_url'),
    path('logout/', LogoutView.as_view(next_page= '/'), name='logout_url')
]

story9/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'index.html')

@login_required
def dashboard(request):
    return render(request, 'dashboard.html')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form' : form})

myapp/templates/dashboard.html
{% extends 'index.html' %}

{% block content %}
    {% if user.is_authenticated %}
    <div class="container">
        <div class="d-flex justify-content-center h-100">
            <div class="card">
                <div class="card-body">
                     <h2>Hai {{user.username}}, bagaimana perkuliahan di Fasilkom?</h2>
                     <button class='btn btn-primary' id="text-nav-oauth">Baik</button>
                     <button class='btn btn-primary' id="text-nav-oauth">!Baik</button>
                     <div class = 'p'>*button diatas hanya pemanis</div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'myapp:logout_url' %}" id = "logout">Logout</a>
                </div>
                
        </div>
    </div>
    {% endif %}
{% endblock %}

myapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <title>Story 9</title>
</head>
<body>
        {% block content %}

        <div class="container">
            <div class="d-flex justify-content-center h-100">
                <div class="card">
                    <div class = "card-body">
                        <div class = 'text-alignment center'><h1>Selamat datang di web Marandi</h1>
                        {% if user.is_authenticated %}
                            <a class='btn btn-primary' href="{% url 'myapp:logout_url' %}" id="text-nav-oauth">Logout</a>
                            {% else %}
                            <a class='btn btn-primary' href="{% url 'myapp:login_url' %}" id="text-nav-oauth">Login</a>
                            <a class='btn btn-primary' href="{% url 'myapp:register_url' %}" id="text-nav-oauth1">Register</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

                    {% endif %}
        {% endblock %}
    
</body>
</html>